### PR TITLE
User guide rebranding

### PR DESCRIPTION
**Pull request by bost-h**
The new logo is missing for now because we are waiting for the marketing team, but apart from that this PR should be reviewable/ready to go.

### CODE REVIEW

**Comment by nicoconstanzo** [comment]
I've noticed a few details that could be fixed:

- Base font size should be 15px
```
html {
    font-size: 15px;
}
```

### Navbar section titles should not be uppercase

Class to fix: `.wy-menu-vertical p.caption`

**Current**:

Screenshot 2019-05-02 at 15 54 06

### Navbar dropdown missing left border

**Marvel mockup**

Screenshot 2019-05-02 at 16 51 22

### Navbar "chevron" size is too big.

The font size should be 9px. Class to fix: `.wy-menu-vertical li a span.toctree-expand, .wy-menu-vertical li.current > a > span.toctree-expand` 

Screenshot 2019-05-02 at 16 53 35

**Comment by nicoconstanzo** [comment]
`.wy-nav-content` padding-top should be 26px. 
Screenshot 2019-05-02 at 16 59 02

**Comment by nicoconstanzo** [comment]
Content background should be #ffffff (currently it's #fcfcfc)

Class to fix: `.wy-nav-content`

**Comment by nicoconstanzo** [comment]
Responsive navbar is missing right border (when screen width is small)

Screenshot 2019-05-02 at 17 07 13

**Comment by nicoconstanzo** [comment]
Title color (h1, h2..) should be `#282828` instead of `#000000`

**Comment by bost-h** [comment]
[ch16881]

**Pull request merged**
