### PR TITLE
Docs for the updated "Sources" user journey

### PR DESCRIPTION
**Pull request by ahervy**
## Summary

This draft PR updates the documentation related to the revamped "Sources" user journey.

### New procedures

Added the following procedures:
- [Retrieving from a file](https://github.com/opendatasoft/ods-documentation/blob/ee21532874997d43d5610756fe69c5e6239efa75/source/publishing_data/01_creating_a_dataset/retrieving_file.rst) includes the 3 existing ways of adding a file data source (from a local file, from a URL, or from an FTP server)
- [Configuring a remote service](https://github.com/opendatasoft/ods-documentation/blob/ee21532874997d43d5610756fe69c5e6239efa75/source/publishing_data/01_creating_a_dataset/configuring_remote_service.rst) includes a generic procedure for connecting to remote services and a link to the [reference documentation for connectors](https://github.com/opendatasoft/ods-documentation/blob/ee21532874997d43d5610756fe69c5e6239efa75/source/publishing_data/04_configuring_a_source/configuring_source.rst)

Reworked the following procedures based on the new Sources wizard:
- [Creating a dataset with media files](https://github.com/opendatasoft/ods-documentation/compare/feature/ch25736/source-v2-documentation?expand=1#diff-e6269d5e1c9d838fd0a8a0d99cb42c51b0ac244d90db249c4bc97de1d9317f1a)
- [Creating a dataset with multiple files](https://github.com/opendatasoft/ods-documentation/compare/feature/ch25736/source-v2-documentation?expand=1#diff-a4cd10527b829df8e651dac540f5ccee14523a918b98aa28e2bdd6d21ac60d62)
- [Federating data](https://github.com/opendatasoft/ods-documentation/compare/feature/ch25736/source-v2-documentation?expand=1#diff-3218a7b3f05fa5cfe0d94dd353787b1b78122c95d1daa0117a5c5ebe1e665bb2)

### Restructured documentation

- Moved the content from [Sourcing data](https://github.com/opendatasoft/ods-documentation/blob/51aa41e8b9ae0f4cf34ee3cf3406af8cc99c1406/source/publishing_data/01_creating_a_dataset/sourcing_data.rst) to other sections:
  - [Creating a dataset](https://github.com/opendatasoft/ods-documentation/blob/ee21532874997d43d5610756fe69c5e6239efa75/source/publishing_data/01_creating_a_dataset/creating_a_dataset.rst) now include the overview of the different ways of adding data sources
  - [Configuring data sources](https://github.com/opendatasoft/ods-documentation/blob/ee21532874997d43d5610756fe69c5e6239efa75/source/publishing_data/04_configuring_a_source/configuring_source.rst) now includes an overview of data sources, how to create or edit them, and a list of available connectors
- Split the [list of available connectors]((https://github.com/opendatasoft/ods-documentation/blob/ee21532874997d43d5610756fe69c5e6239efa75/source/publishing_data/04_configuring_a_source/configuring_source.rst)) into two groups: file connectors and connectors for remote services

### Improved navigation

Added a global "view" of the dataset creation process so that users have the big picture:
- [Creating a dataset](https://github.com/opendatasoft/ods-documentation/blob/ee21532874997d43d5610756fe69c5e6239efa75/source/publishing_data/01_creating_a_dataset/creating_a_dataset.rst)

Added in-page navigation to help users navigate within long pages:
- [Retrieving from a file](https://github.com/opendatasoft/ods-documentation/blob/ee21532874997d43d5610756fe69c5e6239efa75/source/publishing_data/01_creating_a_dataset/retrieving_file.rst) with the 3 existing ways of adding a file data source (from a local file, from a URL, or from an FTP server)
- [Creating a dataset with media files](https://github.com/opendatasoft/ods-documentation/compare/feature/ch25736/source-v2-documentation?expand=1#diff-e6269d5e1c9d838fd0a8a0d99cb42c51b0ac244d90db249c4bc97de1d9317f1aR4-R6)
- [Creating a dataset with multiple files](https://github.com/opendatasoft/ods-documentation/compare/feature/ch25736/source-v2-documentation?expand=1#diff-a4cd10527b829df8e651dac540f5ccee14523a918b98aa28e2bdd6d21ac60d62R4-R5)
- [Federating data](https://github.com/opendatasoft/ods-documentation/compare/feature/ch25736/source-v2-documentation?expand=1#diff-3218a7b3f05fa5cfe0d94dd353787b1b78122c95d1daa0117a5c5ebe1e665bb2R4-R6)

### CODE REVIEW

**Comment by coleopard** [comment]
- JSON Dict is available by default unlike what's written in the Configuring data sources page
- could be great to precise that all datasets have a default name and a default technical id that the user can change or not

**Comment by ahervy** [comment]
> * JSON Dict is available by default unlike what's written in the Configuring data sources page
I removed the note about JSON Dict availability from the Configuring data sources page.
> * could be great to precise that all datasets have a default name and a default technical id that the user can change or not
I added this piece of info to the Creating a dataset page, where the full workflow is detailed.

**Review by coleopard — APPROVED** [review]
Awesome! Thank you

**Comment by ahervy** [comment]
When the time comes, there are some "tweaks" about the user guide's language switcher and search feature to be reverted before merging this PR into `develop`.
You can find more information on [Notion](https://www.notion.so/opendatasoft/tat-actuel-de-la-doc-Sources-Connections-b-ta-1990ed766a164527b8df4925c6014ccd)

**Pull request merged**
