### PR TITLE
[branch ch10041] bump supported version of IE to IE10

### PR DESCRIPTION
**Pull request by jmorel**

### CODE REVIEW

**Comment by jmorel** [comment]
Closed because in the end we didn't need to bump the version of IE supported.

**Comment by vbarbaresi** [comment]
But IE9 is already shown as "not supported" in the front-office 🤔

**Comment by jmorel** [comment]
@richterb what should we do then ? And btw it looks like the header on data is not IE9 compatible either.

**Comment by richterb** [comment]
We should not change anything ;)

We officially support IE9 "in degraded mode". If you come with IE9, we still mention that you'll get "an inferior experience", and we encourage you to change, but it still works. IE8 doesn't work at all for example.

(I agree that the title of the box is ambiguous though, it should probably rather be "Your browser is deprecated" or something)

**Pull request closed without merging**
